// <auto-generated />
using System;
using DataAccess.WorkersDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations.SqliteMigrations
{
    [DbContext(typeof(ResourcesSqliteContext))]
    [Migration("20220204160528_AddingSeedData")]
    partial class AddingSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("DataAccess.Entities.Booking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ResourceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DataAccess.Entities.Resource", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Name");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedAt = new DateTime(2022, 1, 18, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8094),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(5991),
                            Name = "Resource {1}",
                            Quantity = 6
                        },
                        new
                        {
                            ID = 2,
                            CreatedAt = new DateTime(2022, 1, 17, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8696),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8681),
                            Name = "Resource {2}",
                            Quantity = 4
                        },
                        new
                        {
                            ID = 3,
                            CreatedAt = new DateTime(2022, 1, 22, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8710),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8706),
                            Name = "Resource {3}",
                            Quantity = 7
                        },
                        new
                        {
                            ID = 4,
                            CreatedAt = new DateTime(2022, 1, 24, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8715),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8713),
                            Name = "Resource {4}",
                            Quantity = 2
                        },
                        new
                        {
                            ID = 5,
                            CreatedAt = new DateTime(2022, 1, 18, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8720),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8717),
                            Name = "Resource {5}",
                            Quantity = 2
                        },
                        new
                        {
                            ID = 6,
                            CreatedAt = new DateTime(2022, 1, 18, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8735),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8730),
                            Name = "Resource {6}",
                            Quantity = 1
                        },
                        new
                        {
                            ID = 7,
                            CreatedAt = new DateTime(2022, 1, 19, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8740),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8738),
                            Name = "Resource {7}",
                            Quantity = 9
                        },
                        new
                        {
                            ID = 8,
                            CreatedAt = new DateTime(2022, 1, 25, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8745),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8743),
                            Name = "Resource {8}",
                            Quantity = 3
                        },
                        new
                        {
                            ID = 9,
                            CreatedAt = new DateTime(2022, 1, 16, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8750),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8747),
                            Name = "Resource {9}",
                            Quantity = 2
                        },
                        new
                        {
                            ID = 10,
                            CreatedAt = new DateTime(2022, 1, 19, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8757),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8754),
                            Name = "Resource {10}",
                            Quantity = 3
                        },
                        new
                        {
                            ID = 11,
                            CreatedAt = new DateTime(2022, 1, 25, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8761),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8759),
                            Name = "Resource {11}",
                            Quantity = 5
                        },
                        new
                        {
                            ID = 12,
                            CreatedAt = new DateTime(2022, 1, 25, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8766),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8764),
                            Name = "Resource {12}",
                            Quantity = 8
                        },
                        new
                        {
                            ID = 13,
                            CreatedAt = new DateTime(2022, 1, 24, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8771),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8769),
                            Name = "Resource {13}",
                            Quantity = 3
                        },
                        new
                        {
                            ID = 14,
                            CreatedAt = new DateTime(2022, 1, 20, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8776),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8774),
                            Name = "Resource {14}",
                            Quantity = 2
                        },
                        new
                        {
                            ID = 15,
                            CreatedAt = new DateTime(2022, 1, 23, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8781),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8779),
                            Name = "Resource {15}",
                            Quantity = 8
                        },
                        new
                        {
                            ID = 16,
                            CreatedAt = new DateTime(2022, 1, 21, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8786),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8784),
                            Name = "Resource {16}",
                            Quantity = 5
                        },
                        new
                        {
                            ID = 17,
                            CreatedAt = new DateTime(2022, 1, 18, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8791),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8789),
                            Name = "Resource {17}",
                            Quantity = 9
                        },
                        new
                        {
                            ID = 18,
                            CreatedAt = new DateTime(2022, 1, 16, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8797),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8795),
                            Name = "Resource {18}",
                            Quantity = 3
                        },
                        new
                        {
                            ID = 19,
                            CreatedAt = new DateTime(2022, 1, 25, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8802),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 4, 18, 5, 28, 103, DateTimeKind.Local).AddTicks(8800),
                            Name = "Resource {19}",
                            Quantity = 6
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Booking", b =>
                {
                    b.HasOne("DataAccess.Entities.Resource", "Resource")
                        .WithMany("Bookings")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("DataAccess.Entities.Resource", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
