// <auto-generated />
using System;
using DataAccess.WorkersDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations.SqliteMigrations
{
    [DbContext(typeof(ResourcesSqliteContext))]
    [Migration("20220205213720_BookedQtyColumn")]
    partial class BookedQtyColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("DataAccess.Entities.Booking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ResourceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DataAccess.Entities.Resource", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Name");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedAt = new DateTime(2022, 1, 26, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(3841),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(1859),
                            Name = "Resource {1}",
                            Quantity = 4
                        },
                        new
                        {
                            ID = 2,
                            CreatedAt = new DateTime(2022, 1, 19, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4565),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4444),
                            Name = "Resource {2}",
                            Quantity = 6
                        },
                        new
                        {
                            ID = 3,
                            CreatedAt = new DateTime(2022, 1, 22, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4580),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4575),
                            Name = "Resource {3}",
                            Quantity = 9
                        },
                        new
                        {
                            ID = 4,
                            CreatedAt = new DateTime(2022, 1, 23, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4585),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4583),
                            Name = "Resource {4}",
                            Quantity = 7
                        },
                        new
                        {
                            ID = 5,
                            CreatedAt = new DateTime(2022, 1, 19, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4590),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4588),
                            Name = "Resource {5}",
                            Quantity = 1
                        },
                        new
                        {
                            ID = 6,
                            CreatedAt = new DateTime(2022, 1, 21, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4602),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4600),
                            Name = "Resource {6}",
                            Quantity = 2
                        },
                        new
                        {
                            ID = 7,
                            CreatedAt = new DateTime(2022, 1, 21, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4607),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4604),
                            Name = "Resource {7}",
                            Quantity = 2
                        },
                        new
                        {
                            ID = 8,
                            CreatedAt = new DateTime(2022, 1, 17, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4612),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4609),
                            Name = "Resource {8}",
                            Quantity = 2
                        },
                        new
                        {
                            ID = 9,
                            CreatedAt = new DateTime(2022, 1, 23, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4617),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4615),
                            Name = "Resource {9}",
                            Quantity = 9
                        },
                        new
                        {
                            ID = 10,
                            CreatedAt = new DateTime(2022, 1, 17, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4624),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4621),
                            Name = "Resource {10}",
                            Quantity = 5
                        },
                        new
                        {
                            ID = 11,
                            CreatedAt = new DateTime(2022, 1, 18, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4629),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4627),
                            Name = "Resource {11}",
                            Quantity = 7
                        },
                        new
                        {
                            ID = 12,
                            CreatedAt = new DateTime(2022, 1, 18, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4634),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4631),
                            Name = "Resource {12}",
                            Quantity = 9
                        },
                        new
                        {
                            ID = 13,
                            CreatedAt = new DateTime(2022, 1, 25, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4639),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4637),
                            Name = "Resource {13}",
                            Quantity = 1
                        },
                        new
                        {
                            ID = 14,
                            CreatedAt = new DateTime(2022, 1, 18, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4644),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4642),
                            Name = "Resource {14}",
                            Quantity = 1
                        },
                        new
                        {
                            ID = 15,
                            CreatedAt = new DateTime(2022, 1, 21, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4648),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4646),
                            Name = "Resource {15}",
                            Quantity = 2
                        },
                        new
                        {
                            ID = 16,
                            CreatedAt = new DateTime(2022, 1, 26, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4654),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4651),
                            Name = "Resource {16}",
                            Quantity = 3
                        },
                        new
                        {
                            ID = 17,
                            CreatedAt = new DateTime(2022, 1, 20, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4658),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4656),
                            Name = "Resource {17}",
                            Quantity = 1
                        },
                        new
                        {
                            ID = 18,
                            CreatedAt = new DateTime(2022, 1, 18, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4664),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4662),
                            Name = "Resource {18}",
                            Quantity = 4
                        },
                        new
                        {
                            ID = 19,
                            CreatedAt = new DateTime(2022, 1, 19, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4669),
                            IsActive = true,
                            LastModifiedAt = new DateTime(2022, 2, 5, 23, 37, 20, 386, DateTimeKind.Local).AddTicks(4667),
                            Name = "Resource {19}",
                            Quantity = 7
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Booking", b =>
                {
                    b.HasOne("DataAccess.Entities.Resource", "Resource")
                        .WithMany("Bookings")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("DataAccess.Entities.Resource", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
